exec proc_team 'ARG','Argentina','CONMEBOL',FALSE,'Insert'
exec proc_team 'BRA','Brasil','CONMEBOL',FALSE,'Insert'
exec proc_team 'CRC','Costa Rica','CONCACAF',FALSE,'Insert'
exec proc_team 'ESP','España','UEFA',FALSE,'Insert'
exec proc_team 'SEN','Senegal', 'CAF',FALSE,'Insert'
exec proc_team 'ENG','Inglaterra','UEFA',FALSE,'Insert'
exec proc_team 'URU','Uruguay','AFC',FALSE,'Insert'
exec proc_team 'MEX','México','CONCACAF',FALSE,'Insert'

exec proc_team 'ATM','Club Atlético de Madrid','UEFA',TRUE,'Insert'
exec proc_team 'ACM','AC Milan','UEFA',TRUE,'Insert'
exec proc_team 'SAP','Deportivo Saprissa','CONMEBOL',TRUE,'Insert'
exec proc_team 'PSG','Paris Saint Germain','UEFA',TRUE,'Insert'


exec proc_player 'arg1', 'Franco', 'Armani', 'Portero', 'Insert'
exec proc_player 'arg2', 'Emiliano', 'Martinez', 'Portero', 'Insert'
exec proc_player 'arg3', 'Nahuel', 'Molina', 'Lateral Derecho', 'Insert'
exec proc_player 'arg4', 'Crisitan', 'Romero', 'Defensa Central', 'Insert'
exec proc_player 'arg5', 'Lisandro', 'Martinez', 'Defensa Central', 'Insert'
exec proc_player 'arg6', 'Nicolás', 'Otamendi', 'Defensa Central', 'Insert'
exec proc_player 'arg7', 'Rodrigo', 'DePaul', 'Mediocampista', 'Insert'
exec proc_player 'arg8', 'Leandro', 'Paredes', 'Mediocampista', 'Insert'
exec proc_player 'arg9', 'Giovanni', 'Lo Celso', 'Mediocampista', 'Insert'
exec proc_player 'arg10', 'Lionel', 'Messi', 'Mediocampista', 'Insert'
exec proc_player 'arg11', 'Ángel', 'Di María', 'Extremo', 'Insert'
exec proc_player 'arg12', 'Joaquín', 'Correa', 'Extremo', 'Insert'
exec proc_player 'arg13', 'Ángel', 'Correa', 'Extremo', 'Insert'
exec proc_player 'arg14', 'Paulo', 'Dybala', 'Mediocampista', 'Insert'
exec proc_player 'arg15', 'Exequiel', 'Palacios', 'Extremo', 'Insert'
exec proc_player 'arg16', 'Lautaro', 'Martinez', 'Delantero', 'Insert'
exec proc_player 'arg17', 'Julián', 'Álvarez', 'Delantero', 'Insert'
exec proc_player 'arg18', 'Alexis', 'McAllister', 'Mediocampista', 'Insert'
exec proc_player 'arg19', 'Juan', 'Foyth', 'Defensa Central', 'Insert'
exec proc_player 'arg20', 'Nicolás', 'Tagliafico', 'Lateral Izquierdo', 'Insert'


exec proc_player 'bra1', 'Ederson', 'Moraes', 'Portero', 'Insert'
exec proc_player 'bra2', 'Allison', 'Becker', 'Portero', 'Insert'
exec proc_player 'bra3', 'Renan', 'Lodi', 'Lateral Izquierdo', 'Insert'
exec proc_player 'bra4', 'Alex', 'Sandro', 'Defensa Central', 'Insert'
exec proc_player 'bra5', 'Thiago', 'Silva', 'Defensa Central', 'Insert'
exec proc_player 'bra6', 'Eder', 'Militao', 'Defensa Central', 'Insert'
exec proc_player 'bra7', 'Carlos Hernique', 'Casemiro', 'Mediocampista', 'Insert'
exec proc_player 'bra8', 'Fabinho', 'Tavares', 'Mediocampista', 'Insert'
exec proc_player 'bra9', 'Neymar', 'Jr', 'Mediocampista', 'Insert'
exec proc_player 'bra10', 'Philip', 'Coutinho', 'Mediocampista', 'Insert'
exec proc_player 'bra11', 'Vinicius', 'Jr', 'Extremo', 'Insert'
exec proc_player 'bra12', 'Rodrigo', 'Goes', 'Extremo', 'Insert'
exec proc_player 'bra13', 'Raphinha', 'Dias', 'Extremo', 'Insert'
exec proc_player 'bra14', 'Lucas', 'Paquetá', 'Mediocampista', 'Insert'
exec proc_player 'bra15', 'Bruno', 'Guimaraes', 'Extremo', 'Insert'
exec proc_player 'bra16', 'Roberto', 'Firmino', 'Delantero', 'Insert'
exec proc_player 'bra17', 'Richarlison', 'de Andrade', 'Mediocampista', 'Insert'
exec proc_player 'bra18', 'Gabriel', 'Jesus', 'Delantero', 'Insert'
exec proc_player 'bra19', 'Felipe', 'Monteiro', 'Defensa Central', 'Insert'
exec proc_player 'bra20', 'Danilo', '', 'Lateral Izquierdo', 'Insert'


exec proc_player 'crc1', 'Keylor', 'Navas', 'Portero', 'Insert'
exec proc_player 'crc2', 'Patrick', 'Sequeira', 'Portero', 'Insert'
exec proc_player 'crc3', 'Ronald', 'Matarrita', 'Lateral Izquierdo', 'Insert'
exec proc_player 'crc4', 'Franciso', 'Calvo', 'Defensa Central', 'Insert'
exec proc_player 'crc5', 'Juan Pablo', 'Vargas', 'Defensa Central', 'Insert'
exec proc_player 'crc6', 'Oscar', 'Duarte', 'Defensa Central', 'Insert'
exec proc_player 'crc7', 'Yeltsin', 'Tejeda', 'Mediocampista', 'Insert'
exec proc_player 'crc8', 'Celso', 'Borges', 'Mediocampista', 'Insert'
exec proc_player 'crc9', 'Bryan', 'Ruiz', 'Mediocampista', 'Insert'
exec proc_player 'crc10', 'Brandon', 'Aguilera', 'Mediocampista', 'Insert'
exec proc_player 'crc11', 'Jewisson', 'Benette', 'Extremo', 'Insert'
exec proc_player 'crc12', 'Joel', 'Campbell', 'Extremo', 'Insert'
exec proc_player 'crc13', 'Álvaro', 'Zamora', 'Extremo', 'Insert'
exec proc_player 'crc14', 'Daniel', 'Chacón', 'Mediocampista', 'Insert'
exec proc_player 'crc15', 'Carlos', 'Mora', 'Extremo', 'Insert'
exec proc_player 'crc16', 'Anthony', 'Contreras', 'Delantero', 'Insert'
exec proc_player 'crc17', 'Anthony', 'Hernandez', 'Mediocampista', 'Insert'
exec proc_player 'crc18', 'Johan', 'Venegas', 'Delantero', 'Insert'
exec proc_player 'crc19', 'Kendall', 'Waston', 'Defensa Central', 'Insert'
exec proc_player 'crc20', 'Carlos', 'Martinez', 'Lateral Derecho', 'Insert'

exec proc_player 'esp1', 'Roberto', 'Martinez', 'Portero', 'Insert'
exec proc_player 'esp2', 'David', 'De Gea', 'Portero', 'Insert'
exec proc_player 'esp3', 'José', 'Gayá', 'Lateral Izquierdo', 'Insert'
exec proc_player 'esp4', 'Eric', 'García', 'Defensa Central', 'Insert'
exec proc_player 'esp5', 'Íñigo', 'Martinez', 'Defensa Central', 'Insert'
exec proc_player 'esp6', 'Mario', 'Hermoso', 'Defensa Central', 'Insert'
exec proc_player 'esp7', 'Koke', 'Resurección', 'Mediocampista', 'Insert'
exec proc_player 'esp8', 'Saúl', 'Ñíguez', 'Mediocampista', 'Insert'
exec proc_player 'esp9', 'Brahim', 'Díaz', 'Mediocampista', 'Insert'
exec proc_player 'esp10', 'Thiago', 'Alcántara', 'Mediocampista', 'Insert'
exec proc_player 'esp11', 'Ferrán', 'Torres', 'Extremo', 'Insert'
exec proc_player 'esp12', 'Pablo', 'Sarabia', 'Extremo', 'Insert'
exec proc_player 'esp13', 'Dani', 'Olmo', 'Extremo', 'Insert'
exec proc_player 'esp14', 'Pablo', 'Gavi', 'Mediocampista', 'Insert'
exec proc_player 'esp15', 'Ansu', 'Fati', 'Extremo', 'Insert'
exec proc_player 'esp16', 'Álvaro', 'Morata', 'Delantero', 'Insert'
exec proc_player 'esp17', 'Pedri', 'González', 'Mediocampista', 'Insert'
exec proc_player 'esp18', 'Iago', 'Aspas', 'Delantero', 'Insert'
exec proc_player 'esp19', 'Pau', 'Torres', 'Defensa Central', 'Insert'
exec proc_player 'esp20', 'Marcos', 'Llorente', 'Lateral Derecho', 'Insert'

exec proc_player 'sen1', 'Edouard', 'Mendy', 'Portero', 'Insert'
exec proc_player 'sen2', 'Seny', 'Dieng', 'Portero', 'Insert'
exec proc_player 'sen3', 'Fode', 'Ballo-Touré', 'Lateral Izquierdo', 'Insert'
exec proc_player 'sen4', 'Kalidou', 'Koulibaly', 'Defensa Central', 'Insert'
exec proc_player 'sen5', 'Abdou', 'Diallo', 'Defensa Central', 'Insert'
exec proc_player 'sen6', 'Formose', 'Mendy', 'Defensa Central', 'Insert'
exec proc_player 'sen7', 'Pape', 'Gueye', 'Mediocampista', 'Insert'
exec proc_player 'sen8', 'Nampalys', 'Mendy', 'Mediocampista', 'Insert'
exec proc_player 'sen9', 'Chaikhou', 'Kouyaté', 'Mediocampista', 'Insert'
exec proc_player 'sen10', 'Idrissa', 'Gueye', 'Mediocampista', 'Insert'
exec proc_player 'sen11', 'Iliman', 'Ndiaye', 'Extremo', 'Insert'
exec proc_player 'sen12', 'Sadio', 'Mané', 'Extremo', 'Insert'
exec proc_player 'sen13', 'Ismaila', 'Sarr', 'Extremo', 'Insert'
exec proc_player 'sen14', 'Pape', 'Sarr', 'Mediocampista', 'Insert'
exec proc_player 'sen15', 'Mbaye', 'Niang', 'Extremo', 'Insert'
exec proc_player 'sen16', 'Bamba', 'Dieng', 'Delantero', 'Insert'
exec proc_player 'sen17', 'Boulaye', 'Dia', 'Mediocampista', 'Insert'
exec proc_player 'sen18', 'Demba', 'Seck', 'Delantero', 'Insert'
exec proc_player 'sen19', 'Moussa', 'Niakhaté', 'Defensa Central', 'Insert'
exec proc_player 'sen20', 'Saliou', 'Ciss', 'Lateral Derecho', 'Insert'

exec proc_player 'eng1', 'Jordan', 'Pickford', 'Portero', 'Insert'
exec proc_player 'eng2', 'Jordan', 'Henderson', 'Portero', 'Insert'
exec proc_player 'eng3', 'Trent', 'Alexander-Arnold', 'Lateral Izquierdo', 'Insert'
exec proc_player 'eng4', 'Fiyako', 'Tomori', 'Defensa Central', 'Insert'
exec proc_player 'eng5', 'Kyle', 'Walker', 'Defensa Central', 'Insert'
exec proc_player 'eng6', 'Kieran', 'Trippier', 'Defensa Central', 'Insert'
exec proc_player 'eng7', 'Mason', 'Mount', 'Mediocampista', 'Insert'
exec proc_player 'eng8', 'Declan', 'Rice', 'Mediocampista', 'Insert'
exec proc_player 'eng9', 'Callum', 'Hudson-Oddoi', 'Mediocampista', 'Insert'
exec proc_player 'eng10', 'Jude', 'Bellingham', 'Mediocampista', 'Insert'
exec proc_player 'eng11', 'Phil', 'Foden', 'Extremo', 'Insert'
exec proc_player 'eng12', 'Raheem', 'Sterling', 'Extremo', 'Insert'
exec proc_player 'eng13', 'Jack', 'Grealish', 'Extremo', 'Insert'
exec proc_player 'eng14', 'James', 'Milner', 'Mediocampista', 'Insert'
exec proc_player 'eng15', 'Jadon', 'Sancho', 'Extremo', 'Insert'
exec proc_player 'eng16', 'Harry', 'Kane', 'Delantero', 'Insert'
exec proc_player 'eng17', 'Pedri', 'González', 'Mediocampista', 'Insert'
exec proc_player 'eng18', 'Tammy', 'Abraham', 'Delantero', 'Insert'
exec proc_player 'eng19', 'Connor', 'Coady', 'Defensa Central', 'Insert'
exec proc_player 'eng20', 'Resee', 'James', 'Lateral Derecho', 'Insert'

exec proc_player 'uru1', 'Fernando', 'Muslera', 'Portero', 'Insert'
exec proc_player 'uru2', 'Sebastian', 'Sosa', 'Portero', 'Insert'
exec proc_player 'uru3', 'Martín', 'Cáseres', 'Lateral Izquierdo', 'Insert'
exec proc_player 'uru4', 'Diego', 'Godín', 'Defensa Central', 'Insert'
exec proc_player 'uru5', 'Jose María', 'Gimenez', 'Defensa Central', 'Insert'
exec proc_player 'uru6', 'Sebastián', 'Coates', 'Defensa Central', 'Insert'
exec proc_player 'uru7', 'Matías', 'Oliveria', 'Mediocampista', 'Insert'
exec proc_player 'uru8', 'Matías', 'Vecino', 'Mediocampista', 'Insert'
exec proc_player 'uru9', 'Rodrigo', 'Betancur', 'Mediocampista', 'Insert'
exec proc_player 'uru10', 'Federico', 'Valverde', 'Mediocampista', 'Insert'
exec proc_player 'uru11', 'Facundo', 'Pellistri', 'Extremo', 'Insert'
exec proc_player 'uru12', 'Giorgian', 'De Arrascaeta', 'Extremo', 'Insert'
exec proc_player 'uru13', 'Facundo', 'Torres', 'Extremo', 'Insert'
exec proc_player 'uru14', 'Nicolás' 'De la Cruz', 'Mediocampista', 'Insert'
exec proc_player 'uru15', 'Darwin', 'Núñez', 'Extremo', 'Insert'
exec proc_player 'uru16', 'Edinson', 'Cavani', 'Delantero', 'Insert'
exec proc_player 'uru17', 'Lucas', 'Torreira', 'Mediocampista', 'Insert'
exec proc_player 'uru18', 'Luis', 'Suarez', 'Delantero', 'Insert'
exec proc_player 'uru19', 'Matías', 'Viña', 'Defensa Central', 'Insert'
exec proc_player 'uru20', 'Ronald', 'Araújo', 'Lateral Derecho', 'Insert'




exec proc_player 'slo1', 'Jan', 'Oblak', 'Portero', 'Insert'
exec proc_player 'cro2', 'Ivo', 'Grbic', 'Portero', 'Insert'
exec proc_player 'mzq3', 'Reinildo', 'Mandava', 'Lateral Izquierdo', 'Insert'
/*exec proc_player 'uru5', 'Jose María', 'Gimenez', 'Defensa Central', 'Insert'*/
exec proc_player 'mtg5', 'Stefan', 'Savic', 'Defensa Central', 'Insert'
/*exec proc_player 'esp6', 'Mario', 'Hermoso', 'Defensa Central', 'Insert'*/
exec proc_player 'rca1', 'Geoffry', 'Kondogbia', 'Mediocampista', 'Insert'
exec proc_player 'bel5', 'Axel', 'Witsel', 'Mediocampista', 'Insert'
/*exec proc_player 'arg7', 'Rodrigo', 'DePaul', 'Mediocampista', 'Insert'*/
/*exec proc_player 'esp7', 'Koke', 'Resurección', 'Mediocampista', 'Insert'*/
exec proc_player 'bel11', 'Yannick', 'Carrasco', 'Extremo', 'Insert'
/*exec proc_player 'arg13', 'Ángel', 'Correa', 'Extremo', 'Insert'*/
/*exec proc_player 'esp8', 'Saúl', 'Ñíguez', 'Mediocampista', 'Insert'*/
exec proc_player 'por14', 'Joao', 'Félix', 'Mediocampista', 'Insert'
exec proc_player 'bra22', 'Matheus', 'Cunha', 'Extremo', 'Insert'
/*exec proc_player 'esp16', 'Álvaro', 'Morata', 'Delantero', 'Insert'*/
/*exec proc_player 'esp20', 'Marcos', 'Llorente', 'Lateral Derecho', 'Insert'*/
exec proc_player 'fra8', 'Antoine', 'Griezmann', 'Delantero', 'Insert'
/*exec proc_player 'bra19', 'Felipe', 'Monteiro', 'Defensa Central', 'Insert'*/
/*exec proc_player 'arg3', 'Nahuel', 'Molina', 'Lateral Derecho', 'Insert'*/


exec proc_player 'fra1', 'Mike', 'Maignan', 'Portero', 'Insert'
exec proc_player 'rum2', 'Ciprian', 'Tatarusanu', 'Portero', 'Insert'
exec proc_player 'fra3', 'Theo', 'Hernández', 'Lateral Izquierdo', 'Insert'
/*exec proc_player 'eng4', 'Fiyako', 'Tomori', 'Defensa Central', 'Insert'*/
exec proc_player 'den5', 'Simon', 'Kjaer', 'Defensa Central', 'Insert'
exec proc_player 'ita6', 'Matteo', 'Gabbia', 'Defensa Central', 'Insert'
exec proc_player 'alg7', 'Ismael', 'Bennacer', 'Mediocampista', 'Insert'
exec proc_player 'ita8', 'Sandro', 'Tonali', 'Mediocampista', 'Insert'
exec proc_player 'bel9', 'Charles', 'De Kataelere', 'Mediocampista', 'Insert'
/*exec proc_player 'esp9', 'Brahim', 'Díaz', 'Mediocampista', 'Insert'*/
exec proc_player 'por11', 'Rafael', 'Leao', 'Extremo', 'Insert'
exec proc_player 'bel12', 'Alexis', 'Saelemakers', 'Extremo', 'Insert'
exec proc_player 'bra33', 'Junior', 'Messias', 'Extremo', 'Insert'
exec proc_player 'ita14', 'Tomasso', 'Pobega', 'Mediocampista', 'Insert'
exec proc_player 'bel15', 'Divock', 'Origi', 'Extremo', 'Insert'
exec proc_player 'fra16', 'Olivier', 'Giroud', 'Delantero', 'Insert'
exec proc_player 'cro17', 'Ante', 'Rebic', 'Mediocampista', 'Insert'
exec proc_player 'sue18', 'Zlatan', 'Ibrahimovic', 'Delantero', 'Insert'
exec proc_player 'fra19', 'Pierre', 'Kalulu', 'Defensa Central', 'Insert'
exec proc_player 'ita20', 'Davide', 'Calabria', 'Lateral Derecho', 'Insert'